# Generated by Django 2.0.3 on 2018-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180310_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='path',
            field=models.URLField(verbose_name='Path to content'),
        ),
    ]
